### PR TITLE
Added support for variable names with spaces in them

### PR DESCRIPTION
**Pull request by jonathon-love**
Hi Russell,

This commit improves lsmeans handling of variable names with spaces in them.

with thanks

### CODE REVIEW

**Comment by rvlenth** [comment]
Jonathon,

Can you give me an example that illustrates a situation where this is needed? I guess in principle I know it's possible, but I've never used variables with spaces in their names.

Russ

Sent from my iPhone

On Aug 2, 2017, at 7:32 AM, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Russell,

This commit improves lsmeans handling of variable names with spaces in them.

with thanks

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/rvlenth/lsmeans/pull/6

Commit Summary

  *   Added support for variable names with spaces in them

File Changes

  *   A R/reformulate.R<https://github.com/rvlenth/lsmeans/pull/6/files#diff-0> (21)

Patch Links:

  *   https://github.com/rvlenth/lsmeans/pull/6.patch
  *   https://github.com/rvlenth/lsmeans/pull/6.diff

**Comment by jonathon-love** [comment]
hi russ,

```
data('ToothGrowth')
names(ToothGrowth)[2] <- 'sup p'

model <- aov(len ~ `sup p`*dose, data=ToothGrowth)

lsmeans::lsmeans(model, ~`sup p`)
```

**Comment by rvlenth** [comment]
Ok, thanks. I'll consider & test after I get home from JSM & another trip.

Russ

Sent from my iPhone

On Aug 2, 2017, at 9:05 AM, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


hi russ,

data('ToothGrowth')
names(ToothGrowth)[2] <- 'sup p'

model <- aov(len ~ `sup p`*dose, data=ToothGrowth)

lsmeans::lsmeans(model, ~`sup p`)

**Comment by rvlenth** [comment]
Thank you. I have merged this, and will see how it goes.

**Pull request merged**
